export const homeType="HOME_TYPE"
export const recoType="RECO_TYPE"
export const compType="COMP_TYPE"
export const headType="HEAD_TYPE"
export const listType="LIST_TYPE"
export const searchType="SEARCH_LIST"